Add pre commit
sentinel-hub/eo-learn-examples pull request #18
Opened 2023-03-24 16:35 UTC by jgersak

2023-03-25 08:21 UTC, batic reviewed
Looks good, thanks for adding this.

However, there are some lines that are now commented out and weren't before. Could you please check?

2023-03-25 08:21 UTC, batic commented on batch-processing/how_to_lulc/HowToLULC_batch.ipynb
> +    "        # with rasterio.Env(rasterio.session.AWSSession(AWS_session)) as env:\n",
Something fishy is happening here; why did linting comment out this line?

2023-03-25 08:21 UTC, batic commented on poverty-detection-keras/Poverty_Detection_Workflow.ipynb
> +    "        # info_list = np.array(tile_splitter.get_info_list())\n",
Again, something fishy, this probably shouldn't be commented out.

2023-03-25 08:21 UTC, batic commented on poverty-detection-keras/Poverty_Detection_Workflow.ipynb
> +    "    # with open(op.join(ckpt_dir, pred_p[\"model_params_fname\"]), \"r\") as f_model_params:\n",
Again.

2023-03-25 08:21 UTC, batic commented on poverty-detection-keras/Poverty_Detection_Workflow.ipynb
> +    "    # with open(op.join(ckpt_dir, pred_p[\"model_params_fname\"]), \"r\") as f_model_params:\n",
And here as well.

2023-03-25 08:21 UTC, batic commented on poverty-detection-keras/Poverty_Detection_Workflow.ipynb
> +    "        # y_preds = []\n",
Here.

2023-03-27 07:24 UTC, zigaLuksic requested changes
Prior to starting this we agreed that the pre-commit hooks would be formatters only.
If you want to enable flake8 as well, you need to do it in 2 steps (2 PRs).
1. enable formatters
2. enable flake8 and adjust code

Because both steps were combined we now have a HUGE pull request that spans 50 files. Noone can check that your adjustments in step 2. were safe.

Please close this PR and do it in two steps

2023-03-27 07:24 UTC, zigaLuksic commented on super-resolution-fastai/Train.ipynb
why was this removed?

2023-03-27 07:27 UTC, closed without merging